### ISSUE TITLE
Ensure Chains works with the v1 version of TaskRuns and PipelineRuns

### ISSUE THREAD

**Issue by jagathprakash** [tektoncd/chains#665]
Pipelines APIs have been updated to v1 from v1beta1. 
Make sure that these versions work well with Chains.

Starting on the work here, made some issues to track the subtasks: Thanks @aaron-prindle !!

- [ ] https://github.com/tektoncd/chains/issues/985
- [ ] https://github.com/tektoncd/chains/issues/986
- [x] https://github.com/tektoncd/chains/issues/987

**Comment by bendory** [comment]
Context: today chains is only watching `v1beta1` pipelines.

**Comment by lcarva** [comment]
I wonder if it's possible for Chains to handle both v1beta1 and v1. That would facilitate adoption.

**Comment by bendory** [comment]
> I wonder if it's possible for Chains to handle both v1beta1 and v1. That would facilitate adoption.

`+1`

In fact, we need a spin-off issue around handling cross-version compatibility with pipelines changes.

**Comment by vdemeester** [comment]
So, technically, as long as `v1beta1` is served by `tektoncd/pipeline`, `chains` will work because the controller watches `v1beta1` types, which are automatically converted, no matter how the user created them. This means that, today, if a user creates a `v1` type, `chains` will handle it (because it will get it while watching `v1beta1` objects).

I think, in a few release (most likely, more or less at the same time 0.47 gets release with a storage version change), `chains` should switch from watching `v1beta1` to `v1`. This would make `chains` not working with older pipeline version (older than 0.43), but I think at some point this will be fine.

We may want to rename this issue to "switch chains controller to watch `v1` types" instead 👼🏼

**Comment by bendory** [comment]
Immediate AIs:
- [ ] future releases of chains need to include release notes on compatibility with pipeline versions
- [ ] future releases of pipelines need to include release notes on compatibility with chains versions

TEP please:
- [ ] enhance chains and pipelines such that installation of a version incompatible with the existing installation would fail or at least alert to the problem

**Comment by vdemeester** [comment]
@bendory definitely +:100: on your checklist ❤️

**Comment by chitrangpatel** [comment]
Here is the proposed action plan for this:

1. Switch to using `v1`  internally in Chains (throughout)
2. Convert all `v1beta1` objects to `v1`  in the controller/object interface.
3. Wherever there are deprecated things like `pipelineResources` , we could partially convert back to `v1beta1` where needed so that appropriate things can be assessed.

This would completely satisfy `chains/v1`  predicate.

The only issue is with `v2alpha2`  where we embed the complete runSpec. We could leverage the `configMap` for that and depending on the desired version, convert to `v1` or `v1beta1` before sticking it into the provenance.

Eventually, when `v1beta1`  is deprecated, we could remove support for the deprecated fields from Chains.

**Comment by aaron-prindle** [comment]
Starting on the work here, made some issues to track the subtasks:

- [ ] https://github.com/tektoncd/chains/issues/985
- [ ] https://github.com/tektoncd/chains/issues/986
- [ ] https://github.com/tektoncd/chains/issues/987

If someone has comment edit access, feel free to make this an [Umbrella Tracking] issue and put this checklist in the top comment
