### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by priyawadhwa** [tektoncd/chains#74]
Let's release v0.1.0 of chains! Things we should do before then:
- [x] Clarify and document release process https://github.com/tektoncd/chains/issues/72

And it would be nice to have:
- [x]  Better defaults/validation for the configmap https://github.com/tektoncd/chains/issues/71
- [x] Create a separate k8s service account for chains  #68 
- [x] Run the integration tests that require a registry #73
- [x] Support cosign generated private keys for signing  https://github.com/tektoncd/chains/issues/79
