### ISSUE TITLE
v0.2.0 release

### ISSUE THREAD

**Issue by priyawadhwa** [tektoncd/chains#90]
We should include these in the next release:
- [x] Add instructions for authenticating to a registry for the controller https://github.com/tektoncd/chains/issues/86
- [x] ITE-6 as a formatter  https://github.com/tektoncd/chains/issues/65
- [ ] Docs/Readme improvements #102

and it would be nice to have these as well!
- [ ] Figure out ITE-5/SSL Signing Spec integration #75
- [ ] Sign chains releases with chains #84

**Comment by priyawadhwa** [comment]
we did this!
